= Projects Summary

Summaries of projects I'll be doing that I won't mind sharing at some point.
TODO: for relevant oens that I don't mind sharing (most), give them the UNLICENSE

== MLC

A bit of a low-down project. Has some machine learning involved, very cool.

== xrayvault

Basically a web scraper with a leaning towards actually useful types of technical data.
Not a fan of the name.
Think firmware for various devices, installers, source control repositories, software manuals, hardware manuals, specifications, standards, etc.
Does a lot of processing on the data though.
Like unzipping, unarchiving, unpacking filesystems, running `file`, `binwalk`, `binwalk3`, custom analyzers, etc. on each file and unarchived/unzipped file and directory, tagging everything for search and comparisons later.
Want to easily find "similar" files in here.
One feature is to find pieces of one file in others and call that "similarity".
Potentially would query local LLM(s) about some files too to see what they can figure out.
Some things done in the `MLC` project may be useful here.
The `bitdiag` project may also be useful here.

More information is available in the README in the repo.

== bitdiag

"Bit diagnostics".
Basically pattern detection in sets of data.
Ever get like a million packets of some unknown format and you have to manually pick through them figuring out which ones are constants, which ones are counters, how many bits the counter is, whether there are timestamps, etc.?
This will figure that out (some of it at least) for you.

== URAID

User RAID software solution.
Some ideas on how to implement basic data backup solutions without resorting to full on RAID and without stressing out the drives too often.
For the most part, the best solution to this for most people is probably paying for online storage with a vendor that won't delete your data and by encrypting the data yourself first (correctly).
This lets big server farms or whatever deal with the potentially complex tasks related to proper redundancies and backups and long-term data storage.

== Easy Crypto Tools

In URAID, I mentioned encrypting files correctly and yourself.
This project will contain a few solutions that hopefully anyone can use themselves with ease to properly encrypt their data before throwing it in the cloud for safe storage.
This will of course provide the decryption tools for when you want to pull your data down.
All open source so users can review to make sure they're okay with the implementation or in case they want to decrypt it themselves some other way and just need to see data layouts or whatever.
Will also contain some features that make it easy to put encrypted files into, say, GitHub.
I think that's useful to store code you really don't want shared with others a little bit secretly.
In case GitHub or some other source control thing starts to not like that idea and implement preventative measures against that, make it difficult for them to do so (maybe some steg, anti-anti-virus, anti-debugging, anti-RE type stuff)

== Utilitools

Just want a repo with general utilities so I can re-use between projects.
* Logger
* config file loading: yaml, json, ini, toml, xml, maybe env files (and optionally store in actual os.environ or just in config object)
* file watcher
* directory watcher
* file/directory finder: find files that match "type (dir, reg, link, etc.)" and/or "size (or range)" and/or matches regex in basename and/or matches regex in whole path name and/or matches access datetime (or range) and/or modify datetime (or range) and/or change datetie (or range) and/or birth datetime (or range) and/or permissions and or ...
  * max depth
  * see `find` command for ideas
  * multi-threaded/multi-processed
  * whether or not to follow symlinks
  * filename patterns to skip
  * directory name patterns to ski

== notifmotif

Basically just a multi-faceted notification library that is usable in lots of different environments (readline-based CLI applications, tmux-style applications, GUIs, just email notifications about things that happen on your computer, etc.).
Just wanted some of this functionality in more than one other project of mine, so figured I'd make it into a bit of a reusable library.

== Linux Kernel Userspace Crypto

There is a crypto API in userspace on Linux that is implemented in the kernel.
I only recently learned this was a thing.
Why isn't that getting used more rather than OpenSSL, MbedTLS, WolfSSL, etc?
I found the API docs a little...not great, so I just want to create a repo that implements some easy to understand and easy to reuse examples for common ciphers like AES CBC, XTS, GCM, RSA, whatever lese is available.
The source code to cryptsetup (`apt source cryptsetup`) in file `lib/crypto_backend/crypto_cipher_kernel.c` and other nearby files may be a good reference resource.

== GNU Tools in Python

First though was "I wish I could use `grep` in Python without having to call a subprocess."
But also didn't want to re-implement the algorithms in Python because that seems like it would needlessly introduce bugs and would be much slower.
And then I thought maybe we could just easily interface with the existing C functions with Python with some wrapper code so we can re-use the C implementation of this stuff write in Python.
Now why not do this with lots of other GNU tools like gawk, find, ?
Assuming licensing stuff isn't an issue, I think this could be cool.

== Creeper (image and/or video -> location)

Name still TBD, just came up with something quick.
The idea is basically: given an image or a video or multiple images and/or videos, determine where the image or video was taken as precisely as possible.
Basically geoguesser solver type of application, but more general and cool.
This is mostly for if Exif data is gone or is untrusted, but it will probably also summarize that to the user with the a caveat of something like "this is exif data which is easily spoofed".
Want this to attempt to be as precise as possible while yielding some kind of confidence level and if confidence is low and if possible, may yield a list of possibilities (and each might have its own confidence level) that are not very specific (could just be a country or hemisphere or something very big if it can't do better).
Would love to be able to use this in `xrayvault`.

Ideas:

* OCR and try to determine languages used in the file(s), in particular on street signs, buildings, landscape, billboards, etc.
  * Clothing and stuff is also helpful, but not 100%.
* If available, use Exif data to give a hint to area and try to match that info with things found in the image.
* Try to identify astronomical items and use that to estimate location.
E.g., moon and/or sun angle and visibility, how sunny out it is (can indicate rough time of day, so along with sun/moon location, could possibly be useful in location estimation), stars (especially constellations and navigational ones like the North Star).
* See if any GeoGuesser solvers actually do something like this and what do they do.
* Compare the image with Google Earth and Google Maps files.
General photo similarities like building style, street sign styles, road styles, car makes and models, bikes, buses, trucks, terrain (desert, forrest, ocean, etc.), etc.
* Store information for all photos we're certain about and then compare new photos with existing photos to get estimations.
* Also scrape/obtain google review photos and do similar comparisons.
* For indoors places, may be helpful to scrape/obtain social media posts and compare with those.
  * Exif/check-in data on these may be trustworthy enough to seriously consider.
* Even if we cannot determine a ton of information about the location, can notify user if there were similar locations in known photos and show them those photos.
  * Additionally, can use the location information determined from those similar photos to help in identification of the new photo.
* Probably very heavy in ML implementation
* Try to OCR unique identifiers in text/stamps/engravings/etc in the image.
Then, look it up (fuzzy match - anything that's close-ish to the OCR'd value is enough to report on since the OCR may not be perfect).
Hopefully the OCR tool reports some confidence value, which can be used to influence how fuzzy of a match to perform.
Would also need access to a lot of data that may not be easy to find/obtain.
  * To be clear, I mean something similar to what law enforcement does in criminal investigations with identifiers like this.
Like "this serial number was in lot <X> in country <C>, state/city <blah>, and went to stores <here> to be sold or was sent to <this exact user at this exact address> on Amazon".
  * Doesn't actually have to be unique identifiers like serial numbers - if it's something unique enough like a collector's edition or limited release version of something, can also narrow things down.
* There should probably be an ability to mark Exif info for particular images (or a set of images or all images from a particular source, etc.) as unreliable or incorrect and then re-train or re-calculate stuff as necessary.
  * Also could include ability to say "this photo or these photos or all photos from this source are only slightly inaccurate, so weigh them less than other data".
  * Similarly, should be able to mark images (as a human) and the location information as "this is definitely correct and has 100% accuracy" or "this seems almost correct, but it might be a little off (e.g., correct city, but incorrect or unsure about exact location).
    * When ingesting particular data sets, capture certainty/trust level of data from that source and weight the information accordingly.

== Maybes

These are just random ideas I've had that idk if I'll go through with.

=== Multi-platform Screenshot

For each common platform, implement as many "screenshot" implementations as possible.

OS's: Linux, Windows, OSX, Unix

Windows and OSX probably have 1-3 different methods each and have a consistent set of GUI API functions.
So implement maybe once, which possible differences between versions that probably aren't too difficult.

Linux and Unix have many different GUI applications possible.
Maybe make this into a library that basically supports a lot of them and is kinda middleware to provide a common interface that just works no matter where.
Here is how that would work:

* Enumerate logged in users
* Enumerate each screen/display for each user
* Detect the process associated with that display.
* dlopen/dlsym appropriate symbols for that found display.
* Call the appropriate functions to capture screenshot on each screen.

If there's an error in the above, could just try to load all known GUI application symbols and try taking a screenshot with each, which is a little bit brute force and gross, but would be more "sure" to not miss anything.

Linux/Unix graphical applications to try to support:

* GNOME
* KDE
* MATE
* i3
* Etc.

==== Non-GUIs

For example, headless servers.
Unix, Linux, Windows(?), etc.
Capture framebuffer?
There may be some other ways to just capture what's on the terminal screen.

=== Re-implement various servers in Python

As a teaching exercise, implement various servers in Python. Python is simple enough that readers can easily understand what's going on usually.

Example servers:

* FTP (ftpd)
* SFTP (sftpd)
* TFTP (tftpd)
* Basic HTTP server
* Basic HTTPS server?

=== SSH Multi-monitor thing

Basically might be nice to be able to use a machine in another part of the house that has multiple monitors without being at that machine.
The idea is kinda like an SSH/RDP type thing, but auto-detecting the destination machine's monitor setup or something and creating an easy-to-use multi-desktop thing from all of that.
Hopefully without messing up the destination machine's window layouts.
Honestly not sure this is worth doing.

=== Window Session Saving

Like the feature in web browsers that save your last used tabs and then just open them back up when you open the browser again?
Hate it when you have to shut down your machine (laptops) and have to close all of your terminals and VMs and whatnot?
This will basically do the web browser session save thing, but for desktop environments.
Specifically tailored for technical users a bit so as to handle special cases like "what does it mean to 'save' a terminal session?"
Kinda along with the SSH multi-monitor thing, but not really.

=== Browser tab/session saving for private mode

I browse in private mode on my phone pretty much always.
I often open a bunch of tabs on a couple subjects and have to go away and come back to them later.
Unfortunately, sometimes the browser just...dies or auto-updates or some battery saving phone feature decided to kill it or something.
This means I lose those tabs.
Sure, I could just browse in non-private mode, but I like the benefits that private mode gives me.
I just want the ability to save off those tabs so I can come back to them later (still in private mode) and close and forget about them when I'm ready to close and forget about them.

=== Something something git API(s)

I thought about implementing a Python library for interacting with `git` because I was going through the potential tool list for py-gnu-tools project and thought of `git` as a possibility (but won't - doesn't really fit the paradigm I'm thinkinga about).
There seems to already be `GitPython` and `gitoxide`.
TODO: What are git-porcelain and git-plumbing (these are refenced by `GitPython` o pypi site)?

=== Basic Socket Examples

Maybe write some example programs that are useful for beginners for sockets in general, but also for weird types like this (depending on what it is).
Like just generic "TCP server and client" code and generic "UDP server and client" code that everybody looks up all the time.
lsof man page mentions UDPLITE: what is it?
lsof man page mentions "AFS files": what is it?
